add('one-room-schedule','One-room Schedule','Greedy','Medium',
 'Choose the largest number of meetings that fit in one room. A meeting may start exactly when the previous meeting ends.',
 'n, followed by n lines containing start and end.', 'Print the maximum meeting count.', ['1 ≤ n ≤ 100000','0 ≤ start < end ≤ 10^9'],
 'Sort by finishing time, then repeatedly take the earliest-finishing meeting compatible with the last chosen meeting.',
 'O(n log n) time, O(n) storage.', ['Choosing the longest or earliest-starting meeting can block better choices.','The earliest finish leaves the most time for later meetings.'],
 'int n=f.i();long[][]a=new long[n][2];for(int i=0;i<n;i++){a[i][0]=f.l();a[i][1]=f.l();}Arrays.sort(a,Comparator.comparingLong(x->x[1]));long end=-1;int count=0;for(long[]v:a)if(v[0]>=end){count++;end=v[1];}System.out.println(count);',
 'int n;cin>>n;vector<pair<long long,long long>>a(n);for(auto&v:a)cin>>v.second>>v.first;sort(a.begin(),a.end());long long end=-1;int count=0;for(auto v:a)if(v.second>=end){count++;end=v.first;}cout<<count;',
 'n=ni();a=[(ni(),ni()) for _ in range(n)];a.sort(key=lambda v:v[1]);end=-1;count=0\nfor l,r in a:\n if l>=end:count+=1;end=r\nprint(count)',
 ['4\n0 4\n1 2\n2 3\n3 5\n','3\n1 5\n2 6\n3 7\n','1\n0 1\n','3\n0 1\n1 2\n2 3\n','3\n0 2\n0 2\n2 4\n','4\n5 6\n0 1\n3 4\n1 3\n'],['3','1'])

add('reach-the-exit','Reach the Exit','Greedy','Medium',
 'Start at index 0. At index i you may jump forward between 1 and a[i] positions. Decide whether the last index is reachable; a one-element array is already at the exit.',
 'n, followed by n maximum jump lengths.', 'Print YES or NO.', ['1 ≤ n ≤ 200000','0 ≤ jump ≤ 200000'],
 'Maintain the farthest reachable index. If the next index is beyond it, the route is blocked. Otherwise extend the boundary with i+a[i].',
 'O(n) time, O(1) extra space.', ['You do not need to try every jump separately.','A zero is only a problem when the reachable boundary stops there.'],
 'int n=f.i(),reach=0;boolean ok=true;for(int i=0;i<n;i++){int x=f.i();if(i>reach)ok=false;if(ok)reach=Math.max(reach,i+x);}System.out.println(ok?"YES":"NO");',
 'int n;cin>>n;int reach=0;bool ok=true;for(int i=0;i<n;i++){int x;cin>>x;if(i>reach)ok=false;if(ok)reach=max(reach,i+x);}cout<<(ok?"YES":"NO");',
 'n=ni();reach=0;ok=True\nfor i in range(n):\n x=ni()\n if i>reach:ok=False\n if ok:reach=max(reach,i+x)\nprint("YES" if ok else "NO")',
 ['5\n2 3 1 1 0\n','5\n3 2 1 0 4\n','1\n0\n','2\n0 1\n','3\n2 0 0\n','4\n1 1 1 0\n'],['YES','NO'])

add('stair-routes','Stair Routes','Dynamic programming','Easy',
 'A staircase has n steps. Each move climbs one or two steps. Count the distinct move sequences that reach the top, modulo 1000000007. For zero steps, the empty sequence counts once.',
 'One integer n.', 'Print the number of routes modulo 1000000007.', ['0 ≤ n ≤ 1000000'],
 'Every route ends with a one-step move from n−1 or a two-step move from n−2. Keep only the last two counts.',
 'O(n) time, O(1) space.', ['The base cases are ways(0)=1 and ways(1)=1.','Apply the modulus at each addition.'],
 'int n=f.i();long a=1,b=1;for(int i=2;i<=n;i++){long c=(a+b)%1000000007;a=b;b=c;}System.out.println(b);',
 'int n;cin>>n;long long a=1,b=1;for(int i=2;i<=n;i++){long long c=(a+b)%1000000007;a=b;b=c;}cout<<b;',
 'n=ni();a=b=1\nfor _ in range(2,n+1):a,b=b,(a+b)%1000000007\nprint(b)',
 ['4\n','0\n','1\n','2\n','50\n','10000\n'],['5','1'])

add('fewest-tokens','Fewest Tokens','Dynamic programming','Medium',
 'You have unlimited tokens of each listed positive denomination. Find the fewest tokens needed to pay an exact amount.',
 'n and amount, followed by n denominations.', 'Print the minimum token count, or -1 when exact payment is impossible.',
 ['1 ≤ n ≤ 50','0 ≤ amount ≤ 10000','1 ≤ denomination ≤ 10000'],
 'Let dp[x] be the minimum count for amount x. Start with dp[0]=0 and try each denomination as the final token.',
 'O(n × amount) time, O(amount) space.', ['Always taking the biggest token is not generally optimal.','Unreachable amounts need a sentinel larger than any valid answer.'],
 'int n=f.i(),target=f.i();int[]coins=new int[n],dp=new int[target+1];for(int i=0;i<n;i++)coins[i]=f.i();Arrays.fill(dp,target+1);dp[0]=0;for(int x=1;x<=target;x++)for(int c:coins)if(c<=x)dp[x]=Math.min(dp[x],dp[x-c]+1);System.out.println(dp[target]>target?-1:dp[target]);',
 'int n,t;cin>>n>>t;vector<int>c(n),dp(t+1,t+1);for(int&x:c)cin>>x;dp[0]=0;for(int x=1;x<=t;x++)for(int v:c)if(v<=x)dp[x]=min(dp[x],dp[x-v]+1);cout<<(dp[t]>t?-1:dp[t]);',
 'n=ni();t=ni();coins=[ni() for _ in range(n)];dp=[t+1]*(t+1);dp[0]=0\nfor x in range(1,t+1):\n for c in coins:\n  if c<=x:dp[x]=min(dp[x],dp[x-c]+1)\nprint(dp[t] if dp[t]<=t else -1)',
 ['3 6\n1 3 4\n','1 3\n2\n','2 0\n3 5\n','2 7\n2 3\n','1 10\n1\n','3 11\n9 6 5\n'],['2','-1'])

add('spaced-rewards','Spaced Rewards','Dynamic programming','Medium',
 'Pick rewards from a line of stations without choosing adjacent stations. Find the maximum total reward; choosing no station is allowed.',
 'n, followed by n nonnegative rewards.', 'Print the maximum obtainable reward.', ['1 ≤ n ≤ 200000','0 ≤ reward ≤ 10^9'],
 'For each station, either skip it and retain the previous optimum, or take it and add its reward to the optimum two positions back.',
 'O(n) time, O(1) space.', ['Only the previous two optimal totals matter.','Taking the largest individual value is not enough.'],
 'int n=f.i();long a=0,b=0;for(int i=0;i<n;i++){long x=f.l(),c=Math.max(b,a+x);a=b;b=c;}System.out.println(b);',
 'int n;cin>>n;long long a=0,b=0,x;while(n--){cin>>x;long long c=max(b,a+x);a=b;b=c;}cout<<b;',
 'n=ni();a=b=0\nfor _ in range(n):a,b=b,max(b,a+ni())\nprint(b)',
 ['5\n2 7 9 3 1\n','3\n0 0 0\n','1\n8\n','2\n9 2\n','4\n1000000000 0 1000000000 0\n','4\n2 1 1 2\n'],['12','0'])

add('rising-subsequence','Rising Subsequence','Dynamic programming','Medium',
 'Find the length of the longest strictly increasing subsequence. Chosen elements preserve their original order but need not be adjacent.',
 'n, followed by n integers.', 'Print the maximum subsequence length.', ['1 ≤ n ≤ 200000','−10^9 ≤ value ≤ 10^9'],
 'Maintain the smallest possible tail for every subsequence length. Replace the first tail at least as large as each new value, or append if none exists.',
 'O(n log n) time, O(n) space.', ['Equal values cannot extend a strictly increasing sequence.','Binary search the current tails array.'],
 'int n=f.i(),size=0;long[]tails=new long[n];for(int i=0;i<n;i++){long x=f.l();int l=0,r=size;while(l<r){int m=(l+r)/2;if(tails[m]<x)l=m+1;else r=m;}tails[l]=x;if(l==size)size++;}System.out.println(size);',
 'int n;cin>>n;vector<long long>t;while(n--){long long x;cin>>x;auto it=lower_bound(t.begin(),t.end(),x);if(it==t.end())t.push_back(x);else *it=x;}cout<<t.size();',
 'n=ni();tails=[]\nfor _ in range(n):\n x=ni();i=bisect_left(tails,x)\n if i==len(tails):tails.append(x)\n else:tails[i]=x\nprint(len(tails))',
 ['6\n5 1 6 2 3 7\n','4\n2 2 2 2\n','1\n-1\n','4\n4 3 2 1\n','5\n-3 -1 -2 0 1\n','7\n1 7 2 6 3 5 4\n'],['4','1'])

add('shared-sequence','Shared Sequence','Dynamic programming','Medium',
 'Two lowercase strings share some ordered characters. Find the length of their longest common subsequence. Characters may be skipped in either string.',
 'Two nonempty lowercase words.', 'Print the longest common subsequence length.', ['1 ≤ each length ≤ 1000'],
 'Use prefix DP: matching last characters extend the diagonal by one; otherwise take the better result after dropping a character from either prefix. Keep two rows.',
 'O(nm) time, O(m) auxiliary space.', ['A subsequence is not necessarily a substring.','Each DP cell depends on the left, above and upper-left cells.'],
 'String a=f.next(),b=f.next();int[]prev=new int[b.length()+1];for(int i=1;i<=a.length();i++){int[]cur=new int[b.length()+1];for(int j=1;j<=b.length();j++)cur[j]=a.charAt(i-1)==b.charAt(j-1)?prev[j-1]+1:Math.max(prev[j],cur[j-1]);prev=cur;}System.out.println(prev[b.length()]);',
 'string a,b;cin>>a>>b;vector<int>prev(b.size()+1);for(char x:a){vector<int>cur(b.size()+1);for(int j=1;j<=(int)b.size();j++)cur[j]=x==b[j-1]?prev[j-1]+1:max(prev[j],cur[j-1]);prev=move(cur);}cout<<prev.back();',
 'a=next(data);b=next(data);prev=[0]*(len(b)+1)\nfor x in a:\n cur=[0]*(len(b)+1)\n for j,y in enumerate(b,1):cur[j]=prev[j-1]+1 if x==y else max(prev[j],cur[j-1])\n prev=cur\nprint(prev[-1])',
 ['abcde ace\n','abc xyz\n','a a\n','aaaa aa\n','aggtab gxtxayb\n','abc bac\n'],['3','0'])

add('blocked-grid-routes','Blocked Grid Routes','Dynamic programming','Medium',
 'Move from the top-left cell to the bottom-right using only right and down moves. A dot is open and # is blocked. Count valid routes modulo 1000000007.',
 'r and c, followed by r strings of length c.', 'Print the route count modulo 1000000007.', ['1 ≤ r,c ≤ 1000'],
 'Each open cell receives routes from above and left. A blocked cell resets its count to zero. Update one row in place.',
 'O(rc) time, O(c) auxiliary space.', ['A blocked start or finish has zero routes.','The old dp[j] is the count from above, while dp[j−1] is from the left.'],
 'int r=f.i(),c=f.i();long[]dp=new long[c];dp[0]=1;for(int i=0;i<r;i++){String row=f.next();for(int j=0;j<c;j++){if(row.charAt(j)==\'#\')dp[j]=0;else if(j>0)dp[j]=(dp[j]+dp[j-1])%1000000007;}}System.out.println(dp[c-1]);',
 'int r,c;cin>>r>>c;vector<long long>dp(c);dp[0]=1;for(int i=0;i<r;i++){string row;cin>>row;for(int j=0;j<c;j++){if(row[j]==\'#\')dp[j]=0;else if(j>0)dp[j]=(dp[j]+dp[j-1])%1000000007;}}cout<<dp[c-1];',
 'r=ni();c=ni();dp=[0]*c;dp[0]=1\nfor _ in range(r):\n row=next(data)\n for j in range(c):\n  if row[j]=="#":dp[j]=0\n  elif j:dp[j]=(dp[j]+dp[j-1])%1000000007\nprint(dp[-1])',
 ['3 3\n...\n.#.\n...\n','2 2\n#.\n..\n','1 1\n.\n','1 1\n#\n','2 3\n...\n..#\n','3 4\n....\n....\n....\n'],['2','0'])

add('island-map','Island Map','Graphs','Medium',
 'Count islands on a map of 0 (water) and 1 (land). Land cells connect only horizontally or vertically; diagonals do not connect.',
 'r and c, followed by r binary strings of length c.', 'Print the island count.', ['1 ≤ r,c ≤ 500'],
 'Start an iterative flood fill at each unvisited land cell and mark its entire connected component. Each new flood fill contributes one island.',
 'O(rc) time, O(rc) worst-case space.', ['Diagonal contacts are separate islands.','An iterative queue avoids recursion-depth problems on a large island.'],
 'int r=f.i(),c=f.i();char[][]a=new char[r][];for(int i=0;i<r;i++)a[i]=f.next().toCharArray();int count=0;int[]dr={1,-1,0,0},dc={0,0,1,-1};ArrayDeque<Integer>q=new ArrayDeque<>();for(int i=0;i<r;i++)for(int j=0;j<c;j++)if(a[i][j]==\'1\'){count++;a[i][j]=\'0\';q.add(i*c+j);while(!q.isEmpty()){int v=q.remove(),x=v/c,y=v%c;for(int k=0;k<4;k++){int u=x+dr[k],w=y+dc[k];if(u>=0&&u<r&&w>=0&&w<c&&a[u][w]==\'1\'){a[u][w]=\'0\';q.add(u*c+w);}}}}System.out.println(count);',
 'int r,c;cin>>r>>c;vector<string>a(r);for(auto&s:a)cin>>s;int count=0,dr[]={1,-1,0,0},dc[]={0,0,1,-1};queue<pair<int,int>>q;for(int i=0;i<r;i++)for(int j=0;j<c;j++)if(a[i][j]==\'1\'){count++;a[i][j]=\'0\';q.push({i,j});while(!q.empty()){auto[x,y]=q.front();q.pop();for(int k=0;k<4;k++){int u=x+dr[k],v=y+dc[k];if(u>=0&&u<r&&v>=0&&v<c&&a[u][v]==\'1\'){a[u][v]=\'0\';q.push({u,v});}}}}cout<<count;',
 'r=ni();c=ni();a=[list(next(data)) for _ in range(r)];count=0\nfor i in range(r):\n for j in range(c):\n  if a[i][j]!="1":continue\n  count+=1;a[i][j]="0";q=deque([(i,j)])\n  while q:\n   x,y=q.popleft()\n   for u,v in ((x+1,y),(x-1,y),(x,y+1),(x,y-1)):\n    if 0<=u<r and 0<=v<c and a[u][v]=="1":a[u][v]="0";q.append((u,v))\nprint(count)',
 ['3 4\n1100\n0101\n0001\n','2 2\n10\n01\n','1 1\n0\n','1 1\n1\n','2 3\n111\n111\n','3 3\n101\n010\n101\n'],['2','2'])

add('fewest-hops','Fewest Hops','Graphs','Medium',
 'Find the fewest edges needed to travel from s to t in an undirected unweighted graph. Parallel edges are allowed.',
 'n, m, s and t, followed by m lines containing endpoints u and v. Nodes are numbered 0 to n−1.',
 'Print the shortest distance, or -1 if t is unreachable.', ['1 ≤ n ≤ 100000','0 ≤ m ≤ 200000','0 ≤ s,t,u,v < n'],
 'Breadth-first search discovers nodes in nondecreasing distance from the source. Assign each node a distance only on its first visit.',
 'O(n+m) time and space.', ['Every edge has equal weight.','Mark a node when adding it to the queue.'],
 'int n=f.i(),m=f.i(),s=f.i(),t=f.i();List<List<Integer>>a=new ArrayList<>();for(int i=0;i<n;i++)a.add(new ArrayList<>());for(int i=0;i<m;i++){int u=f.i(),v=f.i();a.get(u).add(v);a.get(v).add(u);}int[]d=new int[n];Arrays.fill(d,-1);ArrayDeque<Integer>q=new ArrayDeque<>();d[s]=0;q.add(s);while(!q.isEmpty()){int u=q.remove();for(int v:a.get(u))if(d[v]==-1){d[v]=d[u]+1;q.add(v);}}System.out.println(d[t]);',
 'int n,m,s,t;cin>>n>>m>>s>>t;vector<vector<int>>a(n);while(m--){int u,v;cin>>u>>v;a[u].push_back(v);a[v].push_back(u);}vector<int>d(n,-1);queue<int>q;d[s]=0;q.push(s);while(!q.empty()){int u=q.front();q.pop();for(int v:a[u])if(d[v]==-1){d[v]=d[u]+1;q.push(v);}}cout<<d[t];',
 'n=ni();m=ni();s=ni();t=ni();a=[[] for _ in range(n)]\nfor _ in range(m):\n u=ni();v=ni();a[u].append(v);a[v].append(u)\nd=[-1]*n;d[s]=0;q=deque([s])\nwhile q:\n u=q.popleft()\n for v in a[u]:\n  if d[v]==-1:d[v]=d[u]+1;q.append(v)\nprint(d[t])',
 ['5 4 0 4\n0 1\n1 4\n0 2\n2 3\n','3 1 0 2\n0 1\n','1 0 0 0\n','3 3 0 2\n0 1\n1 2\n0 2\n','2 2 0 1\n0 1\n0 1\n','4 3 3 0\n0 1\n1 2\n2 3\n'],['2','-1'])

add('prerequisite-check','Prerequisite Check','Graphs','Medium',
 'Each directed edge u→v means task u must finish before task v. Determine whether all tasks can be completed. Duplicate prerequisite edges are allowed.',
 'n and m, followed by m directed edges u v.', 'Print YES if all tasks can be completed, otherwise NO.',
 ['1 ≤ n ≤ 100000','0 ≤ m ≤ 200000','0 ≤ u,v < n'],
 'Kahn’s algorithm repeatedly removes zero-indegree tasks. If fewer than n tasks are removed, a directed cycle remains.',
 'O(n+m) time and space.', ['A directed cycle makes completion impossible.','Queue tasks that currently have no unmet prerequisites.'],
 'int n=f.i(),m=f.i();List<List<Integer>>a=new ArrayList<>();for(int i=0;i<n;i++)a.add(new ArrayList<>());int[]deg=new int[n];for(int i=0;i<m;i++){int u=f.i(),v=f.i();a.get(u).add(v);deg[v]++;}ArrayDeque<Integer>q=new ArrayDeque<>();for(int i=0;i<n;i++)if(deg[i]==0)q.add(i);int count=0;while(!q.isEmpty()){int u=q.remove();count++;for(int v:a.get(u))if(--deg[v]==0)q.add(v);}System.out.println(count==n?"YES":"NO");',
 'int n,m;cin>>n>>m;vector<vector<int>>a(n);vector<int>deg(n);while(m--){int u,v;cin>>u>>v;a[u].push_back(v);deg[v]++;}queue<int>q;for(int i=0;i<n;i++)if(!deg[i])q.push(i);int count=0;while(!q.empty()){int u=q.front();q.pop();count++;for(int v:a[u])if(--deg[v]==0)q.push(v);}cout<<(count==n?"YES":"NO");',
 'n=ni();m=ni();a=[[] for _ in range(n)];deg=[0]*n\nfor _ in range(m):u=ni();v=ni();a[u].append(v);deg[v]+=1\nq=deque(i for i in range(n) if deg[i]==0);count=0\nwhile q:\n u=q.popleft();count+=1\n for v in a[u]:\n  deg[v]-=1\n  if deg[v]==0:q.append(v)\nprint("YES" if count==n else "NO")',
 ['4 4\n0 1\n0 2\n1 3\n2 3\n','3 3\n0 1\n1 2\n2 0\n','1 0\n','1 1\n0 0\n','3 2\n0 1\n0 1\n','4 2\n2 3\n3 2\n'],['YES','NO'])

add('connect-the-labs','Connect the Labs','Graphs','Hard',
 'Connect all labs using some of the offered undirected cables at minimum total cost. If the offered cables cannot connect all labs, report failure. Parallel cables are allowed.',
 'n and m, followed by m lines containing u, v and cost.', 'Print the minimum total cost, or -1 if impossible. One lab requires cost 0.',
 ['1 ≤ n ≤ 100000','0 ≤ m ≤ 200000','0 ≤ u,v < n','0 ≤ cost ≤ 10^9'],
 'Kruskal’s algorithm sorts edges by cost and accepts an edge only when it joins different disjoint-set components. A spanning tree needs n−1 accepted edges.',
 'O(m log m) time, O(n+m) space.', ['Taking a cable inside an already connected component creates an unnecessary cycle.','Use path compression and union by size.'],
 'int n=f.i(),m=f.i();long[][]e=new long[m][3];for(int i=0;i<m;i++){e[i][0]=f.i();e[i][1]=f.i();e[i][2]=f.l();}Arrays.sort(e,Comparator.comparingLong(x->x[2]));class DSU{int[]p=new int[n],sz=new int[n];DSU(){for(int i=0;i<n;i++){p[i]=i;sz[i]=1;}}int root(int x){while(x!=p[x]){p[x]=p[p[x]];x=p[x];}return x;}boolean join(int a,int b){a=root(a);b=root(b);if(a==b)return false;if(sz[a]<sz[b]){int t=a;a=b;b=t;}p[b]=a;sz[a]+=sz[b];return true;}}DSU d=new DSU();long cost=0;int used=0;for(long[]v:e)if(d.join((int)v[0],(int)v[1])){cost+=v[2];used++;}System.out.println(used==n-1?cost:-1);',
 'int n,m;cin>>n>>m;vector<tuple<long long,int,int>>e;while(m--){int u,v;long long w;cin>>u>>v>>w;e.push_back({w,u,v});}sort(e.begin(),e.end());vector<int>p(n),sz(n,1);iota(p.begin(),p.end(),0);auto root=[&](int x){while(x!=p[x]){p[x]=p[p[x]];x=p[x];}return x;};long long cost=0;int used=0;for(auto[w,u,v]:e){u=root(u);v=root(v);if(u==v)continue;if(sz[u]<sz[v])swap(u,v);p[v]=u;sz[u]+=sz[v];cost+=w;used++;}cout<<(used==n-1?cost:-1);',
 'n=ni();m=ni();edges=[]\nfor _ in range(m):u=ni();v=ni();w=ni();edges.append((w,u,v))\nedges.sort();p=list(range(n));sz=[1]*n\ndef root(x):\n while x!=p[x]:p[x]=p[p[x]];x=p[x]\n return x\ncost=used=0\nfor w,u,v in edges:\n u=root(u);v=root(v)\n if u==v:continue\n if sz[u]<sz[v]:u,v=v,u\n p[v]=u;sz[u]+=sz[v];cost+=w;used+=1\nprint(cost if used==n-1 else -1)',
 ['4 5\n0 1 4\n1 2 2\n2 3 3\n0 3 10\n0 2 1\n','3 1\n0 1 8\n','1 0\n','2 2\n0 1 9\n0 1 2\n','3 3\n0 0 0\n0 1 0\n1 2 0\n','3 2\n0 1 1000000000\n1 2 1000000000\n'],['6','-1'])

add('tree-floor-totals','Tree Floor Totals','Trees','Easy',
 'A binary tree is stored in array positions: root 0, left child 2i+1, right child 2i+2. A -1 marks a missing node. Print the sum of node values at each occupied depth. A completely empty tree prints EMPTY.',
 'n, followed by n array entries. Every present non-root node has a present parent.', 'Print the sums from root depth downward, separated by spaces, or EMPTY.',
 ['1 ≤ n ≤ 200000','Each entry is -1 or between 0 and 10^9.'],
 'Traverse present nodes using a queue. Process one queue-sized group per depth, summing its values and queuing existing children.',
 'O(n) time, O(n) space.', ['Missing nodes contribute neither values nor children.','Snapshot the queue size to separate levels.'],
 'int n=f.i();long[]a=new long[n];for(int i=0;i<n;i++)a[i]=f.l();ArrayDeque<Integer>q=new ArrayDeque<>();if(a[0]!=-1)q.add(0);StringBuilder out=new StringBuilder();while(!q.isEmpty()){int count=q.size();long sum=0;while(count-->0){int i=q.remove();sum+=a[i];for(int j=2*i+1;j<=2*i+2&&j<n;j++)if(a[j]!=-1)q.add(j);}out.append(sum).append(" ");}System.out.println(out.length()==0?"EMPTY":out.toString());',
 'int n;cin>>n;vector<long long>a(n);for(auto&x:a)cin>>x;queue<int>q;if(a[0]!=-1)q.push(0);if(q.empty())cout<<"EMPTY";while(!q.empty()){int count=q.size();long long sum=0;while(count--){int i=q.front();q.pop();sum+=a[i];for(int j=2*i+1;j<=2*i+2&&j<n;j++)if(a[j]!=-1)q.push(j);}cout<<sum<<" ";}',
 'n=ni();a=[ni() for _ in range(n)];q=deque([0] if a[0]!=-1 else []);out=[]\nwhile q:\n total=0\n for _ in range(len(q)):\n  i=q.popleft();total+=a[i]\n  for j in (2*i+1,2*i+2):\n   if j<n and a[j]!=-1:q.append(j)\n out.append(total)\nprint(" ".join(map(str,out)) if out else "EMPTY")',
 ['7\n5 2 8 1 -1 3 4\n','1\n-1\n','1\n0\n','3\n1 1000000000 1000000000\n','7\n1 -1 2 -1 -1 3 4\n','4\n1 2 3 4\n'],['5 10 8','EMPTY'])

add('longest-tree-route','Longest Tree Route','Trees','Medium',
 'A connected undirected tree contains n nodes. Find the number of edges in its longest simple path.',
 'n, followed by n−1 undirected edges u v. Nodes are numbered 0 to n−1.', 'Print the tree diameter in edges.', ['1 ≤ n ≤ 100000','The input is a valid tree.'],
 'BFS from any node finds an endpoint of a diameter. BFS again from that endpoint; its maximum distance is the diameter.',
 'O(n) time and space.', ['The longest path need not go through node 0.','Use two breadth-first searches to avoid deep recursion.'],
 'int n=f.i();List<List<Integer>>a=new ArrayList<>();for(int i=0;i<n;i++)a.add(new ArrayList<>());for(int i=1;i<n;i++){int u=f.i(),v=f.i();a.get(u).add(v);a.get(v).add(u);}int start=0,answer=0;for(int pass=0;pass<2;pass++){int[]d=new int[n];Arrays.fill(d,-1);d[start]=0;ArrayDeque<Integer>q=new ArrayDeque<>();q.add(start);int far=start;while(!q.isEmpty()){int u=q.remove();if(d[u]>d[far])far=u;for(int v:a.get(u))if(d[v]==-1){d[v]=d[u]+1;q.add(v);}}start=far;answer=d[far];}System.out.println(answer);',
 'int n;cin>>n;vector<vector<int>>a(n);for(int i=1;i<n;i++){int u,v;cin>>u>>v;a[u].push_back(v);a[v].push_back(u);}int start=0,ans=0;for(int pass=0;pass<2;pass++){vector<int>d(n,-1);d[start]=0;queue<int>q;q.push(start);int far=start;while(!q.empty()){int u=q.front();q.pop();if(d[u]>d[far])far=u;for(int v:a[u])if(d[v]==-1){d[v]=d[u]+1;q.push(v);}}start=far;ans=d[far];}cout<<ans;',
 'n=ni();a=[[] for _ in range(n)]\nfor _ in range(n-1):u=ni();v=ni();a[u].append(v);a[v].append(u)\nstart=0;answer=0\nfor _ in range(2):\n d=[-1]*n;d[start]=0;q=deque([start]);far=start\n while q:\n  u=q.popleft()\n  if d[u]>d[far]:far=u\n  for v in a[u]:\n   if d[v]==-1:d[v]=d[u]+1;q.append(v)\n start=far;answer=d[far]\nprint(answer)',
 ['5\n0 1\n1 2\n1 3\n3 4\n','1\n','2\n0 1\n','5\n0 1\n0 2\n0 3\n0 4\n','5\n0 1\n1 2\n2 3\n3 4\n','6\n0 1\n1 2\n0 3\n3 4\n4 5\n'],['3','0'])

add('window-peaks','Window Peaks','Sliding window','Hard',
 'A monitor displays the largest value in every contiguous window of exactly k readings. Compute these peaks in left-to-right window order.',
 'n and k, followed by n integers.', 'Print n−k+1 window maxima.', ['1 ≤ k ≤ n ≤ 200000','−10^9 ≤ value ≤ 10^9'],
 'Keep candidate indices in a deque with decreasing values. Remove expired indices from the front and dominated values from the back. The front is the current maximum.',
 'O(n) time, O(k) auxiliary space beyond input/output.', ['Recomputing each maximum costs O(nk).','The deque should store indices so expired values can be removed.'],
 'int n=f.i(),k=f.i();long[]a=new long[n];ArrayDeque<Integer>q=new ArrayDeque<>();StringBuilder s=new StringBuilder();for(int i=0;i<n;i++){a[i]=f.l();while(!q.isEmpty()&&q.peekFirst()<=i-k)q.removeFirst();while(!q.isEmpty()&&a[q.peekLast()]<=a[i])q.removeLast();q.addLast(i);if(i>=k-1)s.append(a[q.peekFirst()]).append(" ");}System.out.println(s);',
 'int n,k;cin>>n>>k;vector<long long>a(n);deque<int>q;for(int i=0;i<n;i++){cin>>a[i];while(!q.empty()&&q.front()<=i-k)q.pop_front();while(!q.empty()&&a[q.back()]<=a[i])q.pop_back();q.push_back(i);if(i>=k-1)cout<<a[q.front()]<<" ";}',
 'n=ni();k=ni();a=[ni() for _ in range(n)];q=deque();out=[]\nfor i,x in enumerate(a):\n while q and q[0]<=i-k:q.popleft()\n while q and a[q[-1]]<=x:q.pop()\n q.append(i)\n if i>=k-1:out.append(a[q[0]])\nprint(*out)',
 ['6 3\n1 5 2 4 3 8\n','3 1\n-1 -2 -3\n','1 1\n9\n','4 4\n1 9 2 3\n','5 2\n2 2 2 2 2\n','5 3\n-5 -4 -3 -2 -1\n'],['5 5 4 8','-1 -2 -3'])
