add('strongest-segment','Strongest Segment','Arrays','Medium',
 'Find the largest sum of a nonempty contiguous segment of daily gains and losses.',
 'n, followed by n integers.', 'Print the maximum segment sum.', ['1 ≤ n ≤ 200000','−10^9 ≤ value ≤ 10^9'],
 'At each position, either extend the best segment ending at the previous position or start a new segment. Track the best ending value globally.',
 'O(n) time, O(1) auxiliary space.', ['A negative running prefix cannot help the next segment.','Initialize from the first element so all-negative inputs work.'],
 'int n=f.i();long end=f.l(),best=end;for(int i=1;i<n;i++){long x=f.l();end=Math.max(x,end+x);best=Math.max(best,end);}System.out.println(best);',
 'int n;cin>>n;long long e,b,x;cin>>e;b=e;for(int i=1;i<n;i++){cin>>x;e=max(x,e+x);b=max(b,e);}cout<<b;',
 'n=ni();end=best=ni()\nfor _ in range(n-1):\n x=ni();end=max(x,end+x);best=max(best,end)\nprint(best)',
 ['6\n-3 5 -1 4 -8 2\n','3\n-6 -2 -9\n','1\n0\n','3\n1000000000 1000000000 1000000000\n','4\n1 -1 1 -1\n','5\n-2 1 -2 1 5\n'],['8','-2'])

add('pair-budget','Pair Budget','Hashing','Easy',
 'Two different items must exactly use a given budget. Return the zero-based indices of any valid pair, or -1 if none exists. The judge accepts every valid pair and either index order.',
 'n and budget, followed by n item prices.', 'Print two distinct zero-based indices, or -1.',
 ['2 ≤ n ≤ 200000','−10^9 ≤ price, budget ≤ 10^9'],
 'For each price, look up budget minus price among earlier values. Store one index per value. Never reuse the current index.',
 'O(n) expected time, O(n) space.', ['A complement lookup avoids checking every pair.','Insert the current value after checking its complement.'],
 'int n=f.i();long target=f.l();Map<Long,Integer>seen=new HashMap<>();int a=-1,b=-1;for(int i=0;i<n;i++){long x=f.l();if(a==-1&&seen.containsKey(target-x)){a=seen.get(target-x);b=i;}seen.putIfAbsent(x,i);}System.out.println(a==-1?"-1":a+" "+b);',
 'int n;long long t;cin>>n>>t;unordered_map<long long,int>seen;int a=-1,b=-1;for(int i=0;i<n;i++){long long x;cin>>x;if(a==-1&&seen.count(t-x)){a=seen[t-x];b=i;}if(!seen.count(x))seen[x]=i;}if(a==-1)cout<<-1;else cout<<a<<" "<<b;',
 'n=ni();t=ni();seen={};ans=None\nfor i in range(n):\n x=ni()\n if ans is None and t-x in seen:ans=(seen[t-x],i)\n if x not in seen:seen[x]=i\nprint(-1 if ans is None else " ".join(map(str,ans)))',
 ['4 10\n3 7 2 8\n','3 20\n1 2 3\n','2 6\n3 3\n','3 0\n-2 0 2\n','4 4\n2 1 3 2\n','2 -2\n-1 -1\n'],['0 1','-1'],'PAIR_INDICES')

add('merge-arrivals','Merge Arrivals','Two pointers','Easy',
 'Two desks record arrival times in sorted order. Merge both logs, preserving every duplicate.',
 'n and m, followed by n sorted integers and then m sorted integers.', 'Print all n+m values in nondecreasing order.',
 ['0 ≤ n,m ≤ 100000; n+m ≥ 1','−10^9 ≤ value ≤ 10^9'],
 'Compare the next unused value from each log and take the smaller. Once one log ends, append the rest of the other.',
 'O(n+m) time, O(n+m) input storage.', ['Keep one index for each list.','Either input list can be empty.'],
 'int n=f.i(),m=f.i();long[]a=new long[n],b=new long[m];for(int i=0;i<n;i++)a[i]=f.l();for(int i=0;i<m;i++)b[i]=f.l();int i=0,j=0;StringBuilder s=new StringBuilder();while(i<n||j<m){if(j==m||(i<n&&a[i]<=b[j]))s.append(a[i++]);else s.append(b[j++]);s.append(" ");}System.out.println(s);',
 'int n,m;cin>>n>>m;vector<long long>a(n),b(m);for(auto&x:a)cin>>x;for(auto&x:b)cin>>x;int i=0,j=0;while(i<n||j<m){if(j==m||(i<n&&a[i]<=b[j]))cout<<a[i++];else cout<<b[j++];cout<<" ";}',
 'n=ni();m=ni();a=[ni() for _ in range(n)];b=[ni() for _ in range(m)];i=j=0;out=[]\nwhile i<n or j<m:\n if j==m or (i<n and a[i]<=b[j]):out.append(a[i]);i+=1\n else:out.append(b[j]);j+=1\nprint(*out)',
 ['3 3\n1 4 7\n2 4 9\n','0 3\n\n-2 0 5\n','1 0\n8\n','2 2\n1 1\n1 1\n','2 1\n-5 -1\n-3\n','1 1\n9\n1\n'],['1 2 4 4 7 9','-2 0 5'])

add('range-ledger','Range Ledger','Prefix sums','Easy',
 'A ledger receives many sum queries on a fixed array. Answer each inclusive zero-based range efficiently.',
 'n and q; n values; then q lines containing l and r.', 'Print each range sum on a separate line.',
 ['1 ≤ n,q ≤ 100000','0 ≤ l ≤ r < n','−10^9 ≤ value ≤ 10^9'],
 'Build prefix sums with prefix[0]=0. A query [l,r] is prefix[r+1]−prefix[l].',
 'O(n+q) time, O(n) space.', ['Compute cumulative totals once.','A leading zero makes ranges starting at zero straightforward.'],
 'int n=f.i(),q=f.i();long[]p=new long[n+1];for(int i=0;i<n;i++)p[i+1]=p[i]+f.l();StringBuilder s=new StringBuilder();while(q-->0){int l=f.i(),r=f.i();s.append(p[r+1]-p[l]).append("\n");}System.out.print(s);'.replace('"\n"','"\\n"'),
 'int n,q;cin>>n>>q;vector<long long>p(n+1);for(int i=0;i<n;i++){long long x;cin>>x;p[i+1]=p[i]+x;}while(q--){int l,r;cin>>l>>r;cout<<p[r+1]-p[l]<<"\\n";}',
 'n=ni();q=ni();p=[0]\nfor _ in range(n):p.append(p[-1]+ni())\nfor _ in range(q):\n l=ni();r=ni();print(p[r+1]-p[l])',
 ['4 3\n3 -1 5 2\n0 3\n1 2\n2 2\n','1 1\n-7\n0 0\n','3 2\n1000000000 1000000000 1000000000\n0 2\n1 2\n','3 1\n0 0 0\n0 2\n','2 2\n-1 1\n0 1\n1 1\n','5 1\n1 2 3 4 5\n1 3\n'],['9\n4\n5','-7'])

add('balance-point','Balance Point','Prefix sums','Easy',
 'Find the leftmost index whose values strictly to the left and strictly to the right have equal sums. The value at the index is excluded.',
 'n, followed by n integers.', 'Print the leftmost balancing index, or -1.', ['1 ≤ n ≤ 200000','−10^9 ≤ value ≤ 10^9'],
 'Compute the total. At each index compare the running left sum with total minus left sum minus the current value.',
 'O(n) time, O(n) input storage.', ['The balancing element belongs to neither side.','An empty side has sum zero.'],
 'int n=f.i();long[]a=new long[n];long total=0,left=0;for(int i=0;i<n;i++){a[i]=f.l();total+=a[i];}int ans=-1;for(int i=0;i<n;i++){if(left==total-left-a[i]){ans=i;break;}left+=a[i];}System.out.println(ans);',
 'int n;cin>>n;vector<long long>a(n);long long total=0,left=0;for(auto&x:a){cin>>x;total+=x;}int ans=-1;for(int i=0;i<n;i++){if(left==total-left-a[i]){ans=i;break;}left+=a[i];}cout<<ans;',
 'n=ni();a=[ni() for _ in range(n)];total=sum(a);left=0;ans=-1\nfor i,x in enumerate(a):\n if left==total-left-x:ans=i;break\n left+=x\nprint(ans)',
 ['5\n2 3 9 1 4\n','3\n1 2 3\n','1\n99\n','3\n0 0 0\n','3\n-1 1 0\n','4\n1 -1 3 0\n'],['2','-1'])

add('target-stretch','Target Stretch','Hashing','Medium',
 'Find the length of the longest contiguous segment whose sum equals a target. Values may be negative.',
 'n and target, followed by n integers.', 'Print the maximum length, or 0 if no segment qualifies.',
 ['1 ≤ n ≤ 200000','−10^9 ≤ target, value ≤ 10^9'],
 'Store the earliest index for each prefix sum. A prefix difference equal to target defines a matching segment; retaining the earliest prefix maximizes length.',
 'O(n) expected time, O(n) space.', ['A shrinking window does not generally work with negative values.','Start with prefix sum zero at index -1.'],
 'int n=f.i();long t=f.l(),sum=0;int best=0;Map<Long,Integer>first=new HashMap<>();first.put(0L,-1);for(int i=0;i<n;i++){sum+=f.l();if(first.containsKey(sum-t))best=Math.max(best,i-first.get(sum-t));first.putIfAbsent(sum,i);}System.out.println(best);',
 'int n;long long t,s=0;cin>>n>>t;unordered_map<long long,int>first;first[0]=-1;int best=0;for(int i=0;i<n;i++){long long x;cin>>x;s+=x;if(first.count(s-t))best=max(best,i-first[s-t]);if(!first.count(s))first[s]=i;}cout<<best;',
 'n=ni();t=ni();s=0;best=0;first={0:-1}\nfor i in range(n):\n s+=ni()\n if s-t in first:best=max(best,i-first[s-t])\n if s not in first:first[s]=i\nprint(best)',
 ['6 3\n1 -1 3 2 -2 1\n','3 9\n1 1 1\n','1 -5\n-5\n','4 0\n0 0 0 0\n','4 2\n2 -2 2 0\n','5 0\n1 -1 1 -1 4\n'],['5','0'])

add('everyone-else-product','Everyone Else’s Product','Prefix sums','Medium',
 'For every position, print the product of all other array values. Do not use division; zeros are allowed.',
 'n, followed by n integers.', 'Print n products in index order.',
 ['2 ≤ n ≤ 100000','−10 ≤ value ≤ 10','All prefix, suffix and requested products fit signed 64-bit integers.'],
 'Store the prefix product before each index, then multiply it by a running suffix product in a reverse pass.',
 'O(n) time, O(1) auxiliary space beyond input and output.', ['A zero prevents a division-based shortcut.','Each answer is a product from the left and a product from the right.'],
 'int n=f.i();long[]a=new long[n],out=new long[n];long p=1;for(int i=0;i<n;i++){a[i]=f.l();out[i]=p;p*=a[i];}p=1;for(int i=n-1;i>=0;i--){out[i]*=p;p*=a[i];}StringBuilder s=new StringBuilder();for(long x:out)s.append(x).append(" ");System.out.println(s);',
 'int n;cin>>n;vector<long long>a(n),out(n);long long p=1;for(int i=0;i<n;i++){cin>>a[i];out[i]=p;p*=a[i];}p=1;for(int i=n-1;i>=0;i--){out[i]*=p;p*=a[i];}for(auto x:out)cout<<x<<" ";',
 'n=ni();a=[ni() for _ in range(n)];out=[];p=1\nfor x in a:out.append(p);p*=x\np=1\nfor i in range(n-1,-1,-1):out[i]*=p;p*=a[i]\nprint(*out)',
 ['4\n1 2 3 4\n','3\n0 3 5\n','2\n0 0\n','3\n-1 2 -3\n','2\n7 8\n','5\n1 1 1 1 1\n'],['24 12 8 6','15 0 0'])

add('rain-between-roofs','Rain Between Roofs','Two pointers','Hard',
 'Unit-width roof columns form a skyline. After rain, water stays between taller columns. Calculate the total trapped water.',
 'n, followed by n nonnegative column heights.', 'Print the number of trapped unit squares.',
 ['1 ≤ n ≤ 200000','0 ≤ height ≤ 10^9'],
 'Use two pointers with left and right maxima. The smaller boundary determines a safe water level for its side; accumulate the difference and move inward.',
 'O(n) time, O(1) extra space beyond the input.', ['Water above an index is bounded by the smaller maximum on its two sides.','Only the side with the smaller current boundary needs to advance.'],
 'int n=f.i();long[]a=new long[n];for(int i=0;i<n;i++)a[i]=f.l();int l=0,r=n-1;long lm=0,rm=0,ans=0;while(l<=r){if(lm<=rm){lm=Math.max(lm,a[l]);ans+=lm-a[l++];}else{rm=Math.max(rm,a[r]);ans+=rm-a[r--];}}System.out.println(ans);',
 'int n;cin>>n;vector<long long>a(n);for(auto&x:a)cin>>x;int l=0,r=n-1;long long lm=0,rm=0,ans=0;while(l<=r){if(lm<=rm){lm=max(lm,a[l]);ans+=lm-a[l++];}else{rm=max(rm,a[r]);ans+=rm-a[r--];}}cout<<ans;',
 'n=ni();a=[ni() for _ in range(n)];l=0;r=n-1;lm=rm=ans=0\nwhile l<=r:\n if lm<=rm:lm=max(lm,a[l]);ans+=lm-a[l];l+=1\n else:rm=max(rm,a[r]);ans+=rm-a[r];r-=1\nprint(ans)',
 ['5\n3 0 2 0 4\n','4\n1 2 3 4\n','1\n9\n','3\n1000000000 0 1000000000\n','6\n5 1 1 1 1 5\n','3\n0 0 0\n'],['7','0'])

add('consecutive-labels','Consecutive Labels','Hashing','Medium',
 'Find the largest count of consecutive distinct integer labels present in an unsorted list. Their original positions do not matter.',
 'n, followed by n labels.', 'Print the longest consecutive-run length.', ['1 ≤ n ≤ 200000','−10^9 ≤ label ≤ 10^9'],
 'Put values in a set. Start counting only at values with no predecessor. Each value belongs to at most one such scan.',
 'O(n) expected time, O(n) space.', ['Duplicates do not extend a run.','Only a label without a predecessor can start a run.'],
 'int n=f.i();Set<Long>s=new HashSet<>();for(int i=0;i<n;i++)s.add(f.l());int best=0;for(long x:s)if(!s.contains(x-1)){int len=1;while(s.contains(x+len))len++;best=Math.max(best,len);}System.out.println(best);',
 'int n;cin>>n;unordered_set<long long>s;while(n--){long long x;cin>>x;s.insert(x);}int best=0;for(auto x:s)if(!s.count(x-1)){int len=1;while(s.count(x+len))len++;best=max(best,len);}cout<<best;',
 'n=ni();s={ni() for _ in range(n)};best=0\nfor x in s:\n if x-1 not in s:\n  y=x\n  while y in s:y+=1\n  best=max(best,y-x)\nprint(best)',
 ['7\n8 2 4 3 20 1 2\n','3\n5 5 5\n','1\n0\n','5\n-2 -1 0 2 1\n','4\n1 3 5 7\n','3\n1000000000 999999999 999999998\n'],['4','1'])

add('mirror-word','Mirror Word','Strings','Easy',
 'Decide whether a lowercase word reads identically from left to right and right to left.',
 'One lowercase word.', 'Print YES for a palindrome, otherwise NO.', ['1 ≤ length ≤ 200000'],
 'Compare matching characters with pointers starting at both ends and moving inward.', 'O(n) time, O(1) extra space.',
 ['Only symmetric character pairs need checking.','Stop as soon as a pair differs.'],
 'String s=f.next();boolean ok=true;for(int l=0,r=s.length()-1;l<r;l++,r--)if(s.charAt(l)!=s.charAt(r)){ok=false;break;}System.out.println(ok?"YES":"NO");',
 'string s;cin>>s;bool ok=true;for(int l=0,r=(int)s.size()-1;l<r;l++,r--)if(s[l]!=s[r]){ok=false;break;}cout<<(ok?"YES":"NO");',
 's=next(data);l=0;r=len(s)-1;ok=True\nwhile l<r:\n if s[l]!=s[r]:ok=False;break\n l+=1;r-=1\nprint("YES" if ok else "NO")',
 ['level\n','coding\n','a\n','aa\n','abca\n','abccba\n'],['YES','NO'])

add('letter-inventory','Letter Inventory','Strings','Easy',
 'Decide whether two lowercase words contain exactly the same letters with the same multiplicities.',
 'Two lowercase words separated by whitespace.', 'Print YES if one is a rearrangement of the other, otherwise NO.',
 ['1 ≤ each length ≤ 200000'],
 'Count each of the 26 letters in the first word and subtract counts from the second. Every count must be zero.',
 'O(n+m) time, O(1) alphabet space.', ['Matching distinct letters is insufficient when counts differ.','Use an array of size 26.'],
 'String a=f.next(),b=f.next();int[]c=new int[26];for(char x:a.toCharArray())c[x-97]++;for(char x:b.toCharArray())c[x-97]--;boolean ok=true;for(int x:c)if(x!=0)ok=false;System.out.println(ok?"YES":"NO");',
 'string a,b;cin>>a>>b;int c[26]={};for(char x:a)c[x-97]++;for(char x:b)c[x-97]--;bool ok=true;for(int x:c)if(x)ok=false;cout<<(ok?"YES":"NO");',
 'a=next(data);b=next(data)\nprint("YES" if Counter(a)==Counter(b) else "NO")',
 ['listen silent\n','aab abb\n','a a\n','ab abc\n','zzzz zzzz\n','abc cab\n'],['YES','NO'])

add('first-solo-letter','First Solo Letter','Strings','Easy',
 'Find the first character of a lowercase message that occurs exactly once in the entire message.',
 'One lowercase word.', 'Print its zero-based index, or -1 if no character is unique.', ['1 ≤ length ≤ 200000'],
 'Count all letters, then scan the word from the beginning for the first count of one.', 'O(n) time, O(1) alphabet space.',
 ['Determine total frequencies before selecting an index.','A second left-to-right pass preserves the first occurrence rule.'],
 'String s=f.next();int[]c=new int[26];for(char x:s.toCharArray())c[x-97]++;int ans=-1;for(int i=0;i<s.length();i++)if(c[s.charAt(i)-97]==1){ans=i;break;}System.out.println(ans);',
 'string s;cin>>s;int c[26]={};for(char x:s)c[x-97]++;int ans=-1;for(int i=0;i<(int)s.size();i++)if(c[s[i]-97]==1){ans=i;break;}cout<<ans;',
 's=next(data);c=Counter(s)\nprint(next((i for i,x in enumerate(s) if c[x]==1),-1))',
 ['swiss\n','aabbcc\n','a\n','aab\n','abcabcx\n','zazb\n'],['1','-1'])

add('run-notes','Run Notes','Strings','Easy',
 'Compress consecutive equal letters into a letter followed by its run length. Include the number 1 for a one-letter run.',
 'One lowercase word.', 'Print the encoded string without spaces.', ['1 ≤ length ≤ 200000'],
 'Scan maximal groups of identical letters and emit the letter and group size.', 'O(n) time, O(n) output space.',
 ['Count adjacent copies, not total frequency.','Flush the last group after the scan.'],
 'String s=f.next();StringBuilder out=new StringBuilder();for(int i=0;i<s.length();){int j=i+1;while(j<s.length()&&s.charAt(j)==s.charAt(i))j++;out.append(s.charAt(i)).append(j-i);i=j;}System.out.println(out);',
 'string s;cin>>s;for(int i=0;i<(int)s.size();){int j=i+1;while(j<(int)s.size()&&s[j]==s[i])j++;cout<<s[i]<<j-i;i=j;}',
 's=next(data);i=0;out=[]\nwhile i<len(s):\n j=i+1\n while j<len(s) and s[j]==s[i]:j+=1\n out.append(s[i]+str(j-i));i=j\nprint("".join(out))',
 ['aaabbcaaaa\n','abc\n','z\n','aaaaaaaaaaaa\n','abababa\n','zzzaazz\n'],['a3b2c1a4','a1b1c1'])

add('unique-window','Unique Window','Sliding window','Medium',
 'Find the longest contiguous substring with no repeated character in a lowercase message.',
 'One lowercase word.', 'Print the maximum length.', ['1 ≤ length ≤ 200000'],
 'Track the last index of each character. When a character repeats inside the current window, move the left boundary after its earlier occurrence.',
 'O(n) time, O(1) alphabet space.', ['Never move the left boundary backward.','Remember the most recent index of each character.'],
 'String s=f.next();int[]last=new int[26];Arrays.fill(last,-1);int left=0,best=0;for(int i=0;i<s.length();i++){int c=s.charAt(i)-97;left=Math.max(left,last[c]+1);last[c]=i;best=Math.max(best,i-left+1);}System.out.println(best);',
 'string s;cin>>s;vector<int>last(26,-1);int l=0,b=0;for(int i=0;i<(int)s.size();i++){int c=s[i]-97;l=max(l,last[c]+1);last[c]=i;b=max(b,i-l+1);}cout<<b;',
 's=next(data);last={};left=best=0\nfor i,c in enumerate(s):\n left=max(left,last.get(c,-1)+1);last[c]=i;best=max(best,i-left+1)\nprint(best)',
 ['abcaefb\n','aaaa\n','a\n','abba\n','abcdefghijklmnopqrstuvwxyz\n','dvdf\n'],['5','1'])

add('balanced-symbols','Balanced Symbols','Stacks','Easy',
 'A symbol string contains only (), [] and {}. Determine whether every opener is closed by the matching type in correctly nested order.',
 'One nonempty symbol string.', 'Print YES if balanced, otherwise NO.', ['1 ≤ length ≤ 200000'],
 'Push opening symbols on a stack. Each closer must match the top opener. At the end the stack must be empty.',
 'O(n) time, O(n) space.', ['Counting each type is not enough: order matters.','Reject a closer when the stack is empty.'],
 'String s=f.next(),open="([{",close=")] }".replace(" ","");ArrayDeque<Character>st=new ArrayDeque<>();boolean ok=true;for(char c:s.toCharArray()){if(open.indexOf(c)>=0)st.push(c);else if(st.isEmpty()||open.indexOf(st.pop())!=close.indexOf(c)){ok=false;break;}}System.out.println(ok&&st.isEmpty()?"YES":"NO");',
 'string s,op="([{",cl=")]}";cin>>s;vector<char>st;bool ok=true;for(char c:s){if(op.find(c)!=string::npos)st.push_back(c);else if(st.empty()||op.find(st.back())!=cl.find(c)){ok=false;break;}else st.pop_back();}cout<<(ok&&st.empty()?"YES":"NO");',
 's=next(data);st=[];match={")":"(","]":"[","}":"{"};ok=True\nfor c in s:\n if c in "([{":st.append(c)\n elif not st or st.pop()!=match[c]:ok=False;break\nprint("YES" if ok and not st else "NO")',
 ['([]){}\n','([)]\n','(\n',']\n','{{[()]}}\n','()()[]\n'], ['YES','NO'])
